spring:
#  security:
#    user:
#      name: admin
#      password: 123456
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://124.70.38.88:3306/weblog?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: Weblog-HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
#=================================================================
# minio
#=================================================================
minio:
  endpoint: http://124.70.38.88:9000
  accessKey: smallfish
  secretKey: smallfish
  bucketName: weblog

#=================================================================
# Lucene 全文检索
#=================================================================
lucene:
  indexDir: E:\\java_workspace\\project\\lucene-index # lucene 索引存放的位置
