server:
  port: 8080
spring:
  profiles:
    # 默认激活 dev 环境
    active: dev
#  jackson:
    # 若返回字段为空 则不返回
#    default-property-inclusion: non_null
    # 设置日期字段格式
#    date-format: yyyy-MM-dd HH:mm:ss

#=================================================================
# log 日志
#=================================================================
logging:
  config: classpath:logback-weblog.xml
#    "[TraceId: %X{traceId}] %clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) [%thread] %clr(%-40.40logger{39}){cyan} : %msg%n"